services:
  frontend:
    build:
      context: ./docker
      dockerfile: Dockerfile.frontend.dev
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./docker
      dockerfile: Dockerfile.backend.dev
    volumes:
      - ./backend:/go/src
    ports:
      - "8000:8000"
    depends_on:
      - database

  database:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
