services:
  frontend:
    container_name: portfolio_frontend_dev
    build:
      context: ../frontend
      dockerfile: ../docker/Dockerfile.frontend.dev
    volumes:
      - ../frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    container_name: portfolio_backend_dev
    build:
      context: ../backend
      dockerfile: ../docker/Dockerfile.backend.dev
    volumes:
      - ../backend:/go/src
    ports:
      - "8000:8000"
    depends_on:
      - database

  database:
    image: mongo:latest
    container_name: portfolio_mongo_dev
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
