# syntax=docker/dockerfile:1

#############
# build-env #
#############

FROM node:23-11

WORKDIR /app

COPY . .

RUN apt-get update \
  && apt-get install openssh-client -y \
  && apt-get clean

RUN npm install

EXPOSE 3000/tcp

ENTRYPOINT ["npm", "run", "dev"]