# syntax=docker/dockerfile:1

#############
# build-env #
#############

FROM cosmtrek/air:v1.52.3

RUN apt-get update \
  && apt-get install openssh-client -y

WORKDIR /go/src/

COPY . .

ENV MONGODB_URI=mongodb://mongo:27017/

EXPOSE 8000/tcp

ENTRYPOINT ["./scripts/startup.sh", "-dev"]