# syntax=docker/dockerfile:1

#############
# build-env #
#############

FROM cosmtrek/air:v1.63.1

ENV MONGODB_URI=mongodb://database:27017/portfolio

RUN apt-get update \
  && apt-get install openssh-client -y

WORKDIR /go/src/

COPY . .

EXPOSE 8000/tcp

ENTRYPOINT ["./scripts/startup.sh"]