# syntax=docker/dockerfile:1

##################
# build-env-back #
##################

FROM golang:trixie AS back-build-env

LABEL maintainer="Eylexander <me@eylexander.fr>"

ENV MONGODB_URI=mongodb://database:27017/portfolio

WORKDIR /go/src/

COPY ./backend .

## Build server
RUN unset GOPATH && go build -o bin/backend src/cmd/*.go

################
# target image #
################

FROM debian:bookworm-slim

WORKDIR /opt/backend

COPY --from=back-build-env /go/src/bin/backend .

EXPOSE 8000/tcp

ENTRYPOINT [ "/opt/backend/backend" ]