services:
  proxy_old:
    image: nginx:latest
    container_name: portfolio_old_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ${ROOT}/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - portfolio_old_frontend
      - portfolio_old_backend
    networks:
      - portfolio_old_network

  portfolio_old_frontend:
    image: eylexander/portfolio-old-frontend:latest
    container_name: portfolio_old_frontend
    restart: always
    depends_on:
      - portfolio_old_backend
    networks:
      - portfolio_old_network

  portfolio_old_backend:
    image: eylexander/portfolio-old-backend:latest
    container_name: portfolio_old_backend
    restart: always
    environment:
      - MONGODB_URI=mongodb://database_old:27017/
      - APP_VERSION=0.2.0
    depends_on:
      - database_old
    networks:
      - portfolio_old_network

  database_old:
    image: mongo:latest
    container_name: portfolio_old_mongo
    restart: always
    volumes:
      - ../data:/data/db
    networks:
      - portfolio_old_network

networks:
  portfolio_old_network:
    driver: bridge